version: '3.1'

services:
  multi-agent-rag:
    build: .
    ports:
      - "8080:8000"  # Ensure this is correctly mapped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./memory.db:/app/memory.db
      - ./logs/docker_agents:/app/logs
    stdin_open: true
    tty: true
