version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: logs/app.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
loggers:
  uvicorn:
    level: INFO
  uvicorn.access:
    level: INFO
root:
  level: DEBUG
  handlers: [console, file]